---
aws_access_key:
aws_secret_key:
aws_region: us-west-2

# VPC Information
vpc_name: "{{ aws_vpc_name | default('my_vpc') }}"
vpc_cidr_block: "{{ aws_vpc_cidr_block | default('10.0.0.0/16') }}"

# Subnets
public_subnet_cidr: "{{ aws_public_subnet_cidr | default('10.0.0.0/24') }}"
az: "{{ aws_az | default('a') }}"

# Security Group
cidr_ip: "{{ aws_cidr_ip | default('0.0.0.0/0') }}"
sg_rules:
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "{{ cidr_ip }}"
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "{{ cidr_ip }}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{ cidr_ip }}"
  - proto: tcp
    from_port: 5986
    to_port: 5986
    cidr_ip: "{{ cidr_ip }}"
  - proto: tcp
    from_port: 5985
    to_port: 5985
    cidr_ip: "{{ cidr_ip }}"
  - proto: tcp
    from_port: 3389
    to_port: 3389
    cidr_ip: "{{ cidr_ip }}"

# custom
verbose: false
